// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.ActualizarProducto", b =>
                {
                    b.Property<int>("Id_Act_Pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Act_Pro"));

                    b.Property<DateTime>("Fec_Act_Pro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<decimal>("Pre_Act_Pro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Act_Pro");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("Actualizaciones");
                });

            modelBuilder.Entity("Core.Domain.Cliente", b =>
                {
                    b.Property<string>("Ced_Cli")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ape_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cor_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dir_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ruc_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel_Cli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Ced_Cli");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core.Domain.DetalleFactura", b =>
                {
                    b.Property<int>("Id_Det_Fac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Det_Fac"));

                    b.Property<int>("Can_Com")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Act_Pro_Per")
                        .HasColumnType("int");

                    b.Property<int>("Id_Fac_Per")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.HasKey("Id_Det_Fac");

                    b.HasIndex("Id_Act_Pro_Per");

                    b.HasIndex("Id_Fac_Per");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("Core.Domain.EntradaProducto", b =>
                {
                    b.Property<int>("Id_Ent_Pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Ent_Pro"));

                    b.Property<int>("Can_Dis")
                        .HasColumnType("int");

                    b.Property<int>("Can_Ent_Pro")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fec_Ent_Pro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.HasKey("Id_Ent_Pro");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Core.Domain.Factura", b =>
                {
                    b.Property<int>("Id_Fac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Fac"));

                    b.Property<string>("Ced_Cli_Per")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fec_Fac")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Tot_Fac")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Fac");

                    b.HasIndex("Ced_Cli_Per");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Core.Domain.Producto", b =>
                {
                    b.Property<int>("Id_Pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Pro"));

                    b.Property<int>("Can_Pro")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fec_Exp_Pro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom_Pro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Pre_Uni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tip_Pro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Pro");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Core.Domain.ActualizarProducto", b =>
                {
                    b.HasOne("Core.Domain.Producto", "Producto")
                        .WithMany("Actualizaciones")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Domain.DetalleFactura", b =>
                {
                    b.HasOne("Core.Domain.ActualizarProducto", "Actualizacion")
                        .WithMany()
                        .HasForeignKey("Id_Act_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Fac_Per")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Producto", "Producto")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actualizacion");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Domain.EntradaProducto", b =>
                {
                    b.HasOne("Core.Domain.Producto", "Producto")
                        .WithMany("Entradas")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Domain.Factura", b =>
                {
                    b.HasOne("Core.Domain.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("Ced_Cli_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Core.Domain.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Core.Domain.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Core.Domain.Producto", b =>
                {
                    b.Navigation("Actualizaciones");

                    b.Navigation("DetallesFactura");

                    b.Navigation("Entradas");
                });
#pragma warning restore 612, 618
        }
    }
}
